#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 113
#define LARGE_STATE_COUNT 9
#define SYMBOL_COUNT 39
#define ALIAS_COUNT 0
#define TOKEN_COUNT 22
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 8
#define PRODUCTION_ID_COUNT 7

enum ts_symbol_identifiers {
  sym_identifier = 1,
  aux_sym_function_definition_token1 = 2,
  aux_sym_function_definition_token2 = 3,
  aux_sym_function_definition_token3 = 4,
  aux_sym_procedure_definition_token1 = 5,
  aux_sym_procedure_definition_token2 = 6,
  aux_sym_object_definition_token1 = 7,
  aux_sym_object_definition_token2 = 8,
  aux_sym_object_declarator_token1 = 9,
  aux_sym_object_declarator_token2 = 10,
  aux_sym_object_declarator_token3 = 11,
  aux_sym_move_statement_token1 = 12,
  aux_sym_move_statement_token2 = 13,
  aux_sym_unknown_command_statement_token1 = 14,
  sym_number_literal = 15,
  sym_string_literal = 16,
  sym__eol = 17,
  sym_line_comment = 18,
  anon_sym_SLASH_STAR = 19,
  aux_sym_comment_token1 = 20,
  anon_sym_SLASH = 21,
  sym_source_file = 22,
  sym__top_level_code = 23,
  sym_function_definition = 24,
  sym_parameter_list = 25,
  sym_procedure_definition = 26,
  sym_object_definition = 27,
  sym_object_declarator = 28,
  aux_sym__statement_list = 29,
  sym__statement = 30,
  sym_move_statement = 31,
  sym_unknown_command_statement = 32,
  sym__expression = 33,
  sym__literal = 34,
  sym_comment = 35,
  aux_sym_source_file_repeat1 = 36,
  aux_sym_parameter_list_repeat1 = 37,
  aux_sym_unknown_command_statement_repeat1 = 38,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [aux_sym_function_definition_token1] = "keyword",
  [aux_sym_function_definition_token2] = "keyword",
  [aux_sym_function_definition_token3] = "keyword",
  [aux_sym_procedure_definition_token1] = "keyword",
  [aux_sym_procedure_definition_token2] = "keyword",
  [aux_sym_object_definition_token1] = "keyword",
  [aux_sym_object_definition_token2] = "keyword",
  [aux_sym_object_declarator_token1] = "keyword",
  [aux_sym_object_declarator_token2] = "keyword",
  [aux_sym_object_declarator_token3] = "keyword",
  [aux_sym_move_statement_token1] = "keyword",
  [aux_sym_move_statement_token2] = "keyword",
  [aux_sym_unknown_command_statement_token1] = "unknown_command_statement_token1",
  [sym_number_literal] = "number_literal",
  [sym_string_literal] = "string_literal",
  [sym__eol] = "_eol",
  [sym_line_comment] = "line_comment",
  [anon_sym_SLASH_STAR] = "/*",
  [aux_sym_comment_token1] = "comment_token1",
  [anon_sym_SLASH] = "/",
  [sym_source_file] = "source_file",
  [sym__top_level_code] = "_top_level_code",
  [sym_function_definition] = "function_definition",
  [sym_parameter_list] = "parameter_list",
  [sym_procedure_definition] = "procedure_definition",
  [sym_object_definition] = "object_definition",
  [sym_object_declarator] = "object_declarator",
  [aux_sym__statement_list] = "_statement_list",
  [sym__statement] = "_statement",
  [sym_move_statement] = "move_statement",
  [sym_unknown_command_statement] = "unknown_command_statement",
  [sym__expression] = "_expression",
  [sym__literal] = "_literal",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_parameter_list_repeat1] = "parameter_list_repeat1",
  [aux_sym_unknown_command_statement_repeat1] = "unknown_command_statement_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [aux_sym_function_definition_token1] = aux_sym_function_definition_token1,
  [aux_sym_function_definition_token2] = aux_sym_function_definition_token1,
  [aux_sym_function_definition_token3] = aux_sym_function_definition_token1,
  [aux_sym_procedure_definition_token1] = aux_sym_function_definition_token1,
  [aux_sym_procedure_definition_token2] = aux_sym_function_definition_token1,
  [aux_sym_object_definition_token1] = aux_sym_function_definition_token1,
  [aux_sym_object_definition_token2] = aux_sym_function_definition_token1,
  [aux_sym_object_declarator_token1] = aux_sym_function_definition_token1,
  [aux_sym_object_declarator_token2] = aux_sym_function_definition_token1,
  [aux_sym_object_declarator_token3] = aux_sym_function_definition_token1,
  [aux_sym_move_statement_token1] = aux_sym_function_definition_token1,
  [aux_sym_move_statement_token2] = aux_sym_function_definition_token1,
  [aux_sym_unknown_command_statement_token1] = aux_sym_unknown_command_statement_token1,
  [sym_number_literal] = sym_number_literal,
  [sym_string_literal] = sym_string_literal,
  [sym__eol] = sym__eol,
  [sym_line_comment] = sym_line_comment,
  [anon_sym_SLASH_STAR] = anon_sym_SLASH_STAR,
  [aux_sym_comment_token1] = aux_sym_comment_token1,
  [anon_sym_SLASH] = anon_sym_SLASH,
  [sym_source_file] = sym_source_file,
  [sym__top_level_code] = sym__top_level_code,
  [sym_function_definition] = sym_function_definition,
  [sym_parameter_list] = sym_parameter_list,
  [sym_procedure_definition] = sym_procedure_definition,
  [sym_object_definition] = sym_object_definition,
  [sym_object_declarator] = sym_object_declarator,
  [aux_sym__statement_list] = aux_sym__statement_list,
  [sym__statement] = sym__statement,
  [sym_move_statement] = sym_move_statement,
  [sym_unknown_command_statement] = sym_unknown_command_statement,
  [sym__expression] = sym__expression,
  [sym__literal] = sym__literal,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_parameter_list_repeat1] = aux_sym_parameter_list_repeat1,
  [aux_sym_unknown_command_statement_repeat1] = aux_sym_unknown_command_statement_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_function_definition_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_function_definition_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_function_definition_token3] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_procedure_definition_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_procedure_definition_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_object_definition_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_object_definition_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_object_declarator_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_object_declarator_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_object_declarator_token3] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_move_statement_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_move_statement_token2] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_unknown_command_statement_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_number_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__top_level_code] = {
    .visible = false,
    .named = true,
  },
  [sym_function_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_list] = {
    .visible = true,
    .named = true,
  },
  [sym_procedure_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_object_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_object_declarator] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__statement_list] = {
    .visible = false,
    .named = false,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_move_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_unknown_command_statement] = {
    .visible = true,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym__literal] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_parameter_list_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unknown_command_statement_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
  field_parameter_name = 2,
  field_parameter_type = 3,
  field_return_type = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
  [field_parameter_name] = "parameter_name",
  [field_parameter_type] = "parameter_type",
  [field_return_type] = "return_type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 4},
  [4] = {.index = 8, .length = 1},
  [5] = {.index = 9, .length = 2},
  [6] = {.index = 11, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_parameter_name, 0, .inherited = true},
    {field_parameter_type, 0, .inherited = true},
  [2] =
    {field_parameter_name, 1},
    {field_parameter_type, 0},
  [4] =
    {field_parameter_name, 0, .inherited = true},
    {field_parameter_name, 1, .inherited = true},
    {field_parameter_type, 0, .inherited = true},
    {field_parameter_type, 1, .inherited = true},
  [8] =
    {field_name, 1},
  [9] =
    {field_name, 1},
    {field_return_type, 3},
  [11] =
    {field_name, 1},
    {field_return_type, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 2,
  [6] = 6,
  [7] = 7,
  [8] = 6,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 11,
  [19] = 13,
  [20] = 12,
  [21] = 10,
  [22] = 14,
  [23] = 15,
  [24] = 16,
  [25] = 17,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 33,
  [43] = 36,
  [44] = 44,
  [45] = 30,
  [46] = 40,
  [47] = 27,
  [48] = 32,
  [49] = 34,
  [50] = 31,
  [51] = 44,
  [52] = 26,
  [53] = 29,
  [54] = 28,
  [55] = 37,
  [56] = 56,
  [57] = 35,
  [58] = 38,
  [59] = 39,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 64,
  [66] = 66,
  [67] = 66,
  [68] = 68,
  [69] = 68,
  [70] = 70,
  [71] = 71,
  [72] = 71,
  [73] = 70,
  [74] = 74,
  [75] = 74,
  [76] = 76,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 76,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 88,
  [89] = 89,
  [90] = 90,
  [91] = 88,
  [92] = 92,
  [93] = 82,
  [94] = 61,
  [95] = 95,
  [96] = 89,
  [97] = 97,
  [98] = 63,
  [99] = 78,
  [100] = 100,
  [101] = 79,
  [102] = 102,
  [103] = 87,
  [104] = 83,
  [105] = 95,
  [106] = 102,
  [107] = 107,
  [108] = 100,
  [109] = 97,
  [110] = 86,
  [111] = 111,
  [112] = 112,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(8);
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '/') ADVANCE(22);
      if (lookahead == ';') ADVANCE(9);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(2);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ';') ADVANCE(9);
      if (lookahead == '|') ADVANCE(14);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(15);
      if (('\t' <= lookahead && lookahead <= '\f') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(19);
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(21);
      if (lookahead == '/') ADVANCE(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(20);
      if (lookahead == '/') ADVANCE(17);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 7:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_unknown_command_statement_token1);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_number_literal);
      if (lookahead == '.') ADVANCE(7);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_number_literal);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_string_literal);
      if (lookahead == '"') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__eol);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__eol);
      if (lookahead == '|') ADVANCE(14);
      if (lookahead == '\n' ||
          lookahead == '\r') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead == '/') ADVANCE(18);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead == '\n') ADVANCE(5);
      if (lookahead == '*') ADVANCE(16);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_SLASH_STAR);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_comment_token1);
      if (lookahead == '*') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '/') ADVANCE(5);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_SLASH);
      if (lookahead == '*') ADVANCE(19);
      if (lookahead == '/') ADVANCE(18);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'A', 1,
        'a', 1,
        'C', 2,
        'c', 2,
        'E', 3,
        'e', 3,
        'F', 4,
        'f', 4,
        'I', 5,
        'i', 5,
        'M', 6,
        'm', 6,
        'O', 7,
        'o', 7,
        'P', 8,
        'p', 8,
        'R', 9,
        'r', 9,
        'T', 10,
        't', 10,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(aux_sym_object_declarator_token3);
      END_STATE();
    case 2:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 3:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(12);
      END_STATE();
    case 4:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 5:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(14);
      END_STATE();
    case 6:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(16);
      END_STATE();
    case 8:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(17);
      END_STATE();
    case 9:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(18);
      END_STATE();
    case 10:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 11:
      if (lookahead == '_') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(21);
      END_STATE();
    case 13:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(22);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(aux_sym_object_declarator_token2);
      END_STATE();
    case 15:
      if (lookahead == 'V' ||
          lookahead == 'v') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'J' ||
          lookahead == 'j') ADVANCE(24);
      END_STATE();
    case 17:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(25);
      END_STATE();
    case 18:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(26);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_move_statement_token2);
      END_STATE();
    case 20:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(27);
      END_STATE();
    case 21:
      if (lookahead == '_') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(29);
      END_STATE();
    case 23:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(30);
      END_STATE();
    case 24:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(31);
      END_STATE();
    case 25:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(32);
      END_STATE();
    case 26:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(34);
      END_STATE();
    case 28:
      if (lookahead == 'F' ||
          lookahead == 'f') ADVANCE(35);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(36);
      if (lookahead == 'P' ||
          lookahead == 'p') ADVANCE(37);
      END_STATE();
    case 29:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(38);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_move_statement_token1);
      END_STATE();
    case 31:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(39);
      END_STATE();
    case 32:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(40);
      END_STATE();
    case 33:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(41);
      END_STATE();
    case 34:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(42);
      END_STATE();
    case 35:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(43);
      END_STATE();
    case 36:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(44);
      END_STATE();
    case 37:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 38:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(46);
      END_STATE();
    case 39:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(47);
      END_STATE();
    case 40:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(48);
      END_STATE();
    case 41:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(49);
      END_STATE();
    case 42:
      if (lookahead == '_') ADVANCE(50);
      END_STATE();
    case 43:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(51);
      END_STATE();
    case 44:
      if (lookahead == 'J' ||
          lookahead == 'j') ADVANCE(52);
      END_STATE();
    case 45:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(53);
      END_STATE();
    case 46:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(54);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_object_declarator_token1);
      END_STATE();
    case 48:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(55);
      END_STATE();
    case 49:
      if (lookahead == 'S' ||
          lookahead == 's') ADVANCE(56);
      END_STATE();
    case 50:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(57);
      END_STATE();
    case 51:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(58);
      END_STATE();
    case 52:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 53:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(60);
      END_STATE();
    case 54:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(61);
      END_STATE();
    case 55:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(62);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_function_definition_token2);
      END_STATE();
    case 57:
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(63);
      END_STATE();
    case 58:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(64);
      END_STATE();
    case 59:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(65);
      END_STATE();
    case 60:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_function_definition_token1);
      END_STATE();
    case 62:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(67);
      END_STATE();
    case 63:
      if (lookahead == 'J' ||
          lookahead == 'j') ADVANCE(68);
      END_STATE();
    case 64:
      if (lookahead == 'I' ||
          lookahead == 'i') ADVANCE(69);
      END_STATE();
    case 65:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(70);
      END_STATE();
    case 66:
      if (lookahead == 'D' ||
          lookahead == 'd') ADVANCE(71);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(aux_sym_procedure_definition_token1);
      END_STATE();
    case 68:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 69:
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(73);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(aux_sym_object_definition_token1);
      END_STATE();
    case 71:
      if (lookahead == 'U' ||
          lookahead == 'u') ADVANCE(74);
      END_STATE();
    case 72:
      if (lookahead == 'C' ||
          lookahead == 'c') ADVANCE(75);
      END_STATE();
    case 73:
      if (lookahead == 'N' ||
          lookahead == 'n') ADVANCE(76);
      END_STATE();
    case 74:
      if (lookahead == 'R' ||
          lookahead == 'r') ADVANCE(77);
      END_STATE();
    case 75:
      if (lookahead == 'T' ||
          lookahead == 't') ADVANCE(78);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym_function_definition_token3);
      END_STATE();
    case 77:
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(aux_sym_object_definition_token2);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(aux_sym_procedure_definition_token2);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 1},
  [63] = {.lex_state = 1},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 1},
  [67] = {.lex_state = 1},
  [68] = {.lex_state = 0},
  [69] = {.lex_state = 0},
  [70] = {.lex_state = 0},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 1},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 1},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 1},
  [79] = {.lex_state = 1},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 1},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 1},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 1},
  [92] = {.lex_state = 4},
  [93] = {.lex_state = 1},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 0},
  [96] = {.lex_state = 0},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 0},
  [101] = {.lex_state = 1},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [aux_sym_function_definition_token1] = ACTIONS(1),
    [aux_sym_function_definition_token2] = ACTIONS(1),
    [aux_sym_function_definition_token3] = ACTIONS(1),
    [aux_sym_procedure_definition_token1] = ACTIONS(1),
    [aux_sym_procedure_definition_token2] = ACTIONS(1),
    [aux_sym_object_definition_token1] = ACTIONS(1),
    [aux_sym_object_definition_token2] = ACTIONS(1),
    [aux_sym_object_declarator_token1] = ACTIONS(1),
    [aux_sym_object_declarator_token2] = ACTIONS(1),
    [aux_sym_object_declarator_token3] = ACTIONS(1),
    [aux_sym_move_statement_token1] = ACTIONS(1),
    [aux_sym_move_statement_token2] = ACTIONS(1),
    [aux_sym_unknown_command_statement_token1] = ACTIONS(1),
    [sym_number_literal] = ACTIONS(1),
    [sym_string_literal] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
    [anon_sym_SLASH] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(85),
    [sym__top_level_code] = STATE(49),
    [sym_function_definition] = STATE(57),
    [sym_procedure_definition] = STATE(57),
    [sym_object_definition] = STATE(57),
    [sym_object_declarator] = STATE(2),
    [sym__statement] = STATE(57),
    [sym_move_statement] = STATE(52),
    [sym_unknown_command_statement] = STATE(52),
    [sym__expression] = STATE(62),
    [sym__literal] = STATE(61),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_unknown_command_statement_repeat1] = STATE(44),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_identifier] = ACTIONS(9),
    [aux_sym_function_definition_token1] = ACTIONS(11),
    [aux_sym_procedure_definition_token1] = ACTIONS(13),
    [aux_sym_object_declarator_token1] = ACTIONS(15),
    [aux_sym_move_statement_token1] = ACTIONS(17),
    [sym_number_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [2] = {
    [sym__top_level_code] = STATE(34),
    [sym_function_definition] = STATE(35),
    [sym_procedure_definition] = STATE(35),
    [sym_object_definition] = STATE(35),
    [sym_object_declarator] = STATE(5),
    [sym__statement] = STATE(35),
    [sym_move_statement] = STATE(26),
    [sym_unknown_command_statement] = STATE(26),
    [sym__expression] = STATE(62),
    [sym__literal] = STATE(61),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_unknown_command_statement_repeat1] = STATE(51),
    [sym_identifier] = ACTIONS(9),
    [aux_sym_function_definition_token1] = ACTIONS(21),
    [aux_sym_procedure_definition_token1] = ACTIONS(23),
    [aux_sym_object_definition_token1] = ACTIONS(25),
    [aux_sym_object_definition_token2] = ACTIONS(25),
    [aux_sym_object_declarator_token1] = ACTIONS(15),
    [aux_sym_move_statement_token1] = ACTIONS(27),
    [sym_number_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [3] = {
    [sym__top_level_code] = STATE(34),
    [sym_function_definition] = STATE(35),
    [sym_procedure_definition] = STATE(35),
    [sym_object_definition] = STATE(35),
    [sym_object_declarator] = STATE(5),
    [sym__statement] = STATE(35),
    [sym_move_statement] = STATE(26),
    [sym_unknown_command_statement] = STATE(26),
    [sym__expression] = STATE(62),
    [sym__literal] = STATE(61),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_unknown_command_statement_repeat1] = STATE(51),
    [sym_identifier] = ACTIONS(9),
    [aux_sym_function_definition_token1] = ACTIONS(21),
    [aux_sym_procedure_definition_token1] = ACTIONS(23),
    [aux_sym_object_definition_token1] = ACTIONS(29),
    [aux_sym_object_definition_token2] = ACTIONS(29),
    [aux_sym_object_declarator_token1] = ACTIONS(15),
    [aux_sym_move_statement_token1] = ACTIONS(27),
    [sym_number_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [4] = {
    [sym__top_level_code] = STATE(34),
    [sym_function_definition] = STATE(35),
    [sym_procedure_definition] = STATE(35),
    [sym_object_definition] = STATE(35),
    [sym_object_declarator] = STATE(5),
    [sym__statement] = STATE(35),
    [sym_move_statement] = STATE(26),
    [sym_unknown_command_statement] = STATE(26),
    [sym__expression] = STATE(62),
    [sym__literal] = STATE(61),
    [sym_comment] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_unknown_command_statement_repeat1] = STATE(51),
    [sym_identifier] = ACTIONS(9),
    [aux_sym_function_definition_token1] = ACTIONS(21),
    [aux_sym_procedure_definition_token1] = ACTIONS(23),
    [aux_sym_object_definition_token1] = ACTIONS(31),
    [aux_sym_object_definition_token2] = ACTIONS(31),
    [aux_sym_object_declarator_token1] = ACTIONS(15),
    [aux_sym_move_statement_token1] = ACTIONS(27),
    [sym_number_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [5] = {
    [sym__top_level_code] = STATE(34),
    [sym_function_definition] = STATE(35),
    [sym_procedure_definition] = STATE(35),
    [sym_object_definition] = STATE(35),
    [sym_object_declarator] = STATE(5),
    [sym__statement] = STATE(35),
    [sym_move_statement] = STATE(26),
    [sym_unknown_command_statement] = STATE(26),
    [sym__expression] = STATE(62),
    [sym__literal] = STATE(61),
    [sym_comment] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_unknown_command_statement_repeat1] = STATE(51),
    [sym_identifier] = ACTIONS(9),
    [aux_sym_function_definition_token1] = ACTIONS(21),
    [aux_sym_procedure_definition_token1] = ACTIONS(23),
    [aux_sym_object_definition_token1] = ACTIONS(33),
    [aux_sym_object_definition_token2] = ACTIONS(33),
    [aux_sym_object_declarator_token1] = ACTIONS(15),
    [aux_sym_move_statement_token1] = ACTIONS(27),
    [sym_number_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [6] = {
    [sym__top_level_code] = STATE(34),
    [sym_function_definition] = STATE(35),
    [sym_procedure_definition] = STATE(35),
    [sym_object_definition] = STATE(35),
    [sym_object_declarator] = STATE(5),
    [sym__statement] = STATE(35),
    [sym_move_statement] = STATE(26),
    [sym_unknown_command_statement] = STATE(26),
    [sym__expression] = STATE(62),
    [sym__literal] = STATE(61),
    [sym_comment] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_unknown_command_statement_repeat1] = STATE(51),
    [sym_identifier] = ACTIONS(35),
    [aux_sym_function_definition_token1] = ACTIONS(38),
    [aux_sym_procedure_definition_token1] = ACTIONS(41),
    [aux_sym_object_definition_token1] = ACTIONS(44),
    [aux_sym_object_definition_token2] = ACTIONS(44),
    [aux_sym_object_declarator_token1] = ACTIONS(46),
    [aux_sym_move_statement_token1] = ACTIONS(49),
    [sym_number_literal] = ACTIONS(52),
    [sym_string_literal] = ACTIONS(52),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [7] = {
    [sym__top_level_code] = STATE(49),
    [sym_function_definition] = STATE(57),
    [sym_procedure_definition] = STATE(57),
    [sym_object_definition] = STATE(57),
    [sym_object_declarator] = STATE(2),
    [sym__statement] = STATE(57),
    [sym_move_statement] = STATE(52),
    [sym_unknown_command_statement] = STATE(52),
    [sym__expression] = STATE(62),
    [sym__literal] = STATE(61),
    [sym_comment] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_unknown_command_statement_repeat1] = STATE(44),
    [ts_builtin_sym_end] = ACTIONS(55),
    [sym_identifier] = ACTIONS(9),
    [aux_sym_function_definition_token1] = ACTIONS(11),
    [aux_sym_procedure_definition_token1] = ACTIONS(13),
    [aux_sym_object_declarator_token1] = ACTIONS(15),
    [aux_sym_move_statement_token1] = ACTIONS(17),
    [sym_number_literal] = ACTIONS(19),
    [sym_string_literal] = ACTIONS(19),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
  [8] = {
    [sym__top_level_code] = STATE(49),
    [sym_function_definition] = STATE(57),
    [sym_procedure_definition] = STATE(57),
    [sym_object_definition] = STATE(57),
    [sym_object_declarator] = STATE(2),
    [sym__statement] = STATE(57),
    [sym_move_statement] = STATE(52),
    [sym_unknown_command_statement] = STATE(52),
    [sym__expression] = STATE(62),
    [sym__literal] = STATE(61),
    [sym_comment] = STATE(8),
    [aux_sym_source_file_repeat1] = STATE(8),
    [aux_sym_unknown_command_statement_repeat1] = STATE(44),
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_identifier] = ACTIONS(35),
    [aux_sym_function_definition_token1] = ACTIONS(59),
    [aux_sym_procedure_definition_token1] = ACTIONS(62),
    [aux_sym_object_declarator_token1] = ACTIONS(46),
    [aux_sym_move_statement_token1] = ACTIONS(65),
    [sym_number_literal] = ACTIONS(52),
    [sym_string_literal] = ACTIONS(52),
    [sym_line_comment] = ACTIONS(3),
    [anon_sym_SLASH_STAR] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(68), 1,
      sym_identifier,
    ACTIONS(73), 1,
      aux_sym_move_statement_token1,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(71), 2,
      aux_sym_function_definition_token3,
      aux_sym_procedure_definition_token2,
    ACTIONS(76), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(9), 2,
      aux_sym__statement_list,
      sym_comment,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [41] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(79), 1,
      aux_sym_procedure_definition_token2,
    STATE(9), 1,
      aux_sym__statement_list,
    STATE(10), 1,
      sym_comment,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [83] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(81), 1,
      aux_sym_procedure_definition_token2,
    STATE(10), 1,
      aux_sym__statement_list,
    STATE(11), 1,
      sym_comment,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [125] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(83), 1,
      aux_sym_function_definition_token3,
    STATE(12), 1,
      sym_comment,
    STATE(15), 1,
      aux_sym__statement_list,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [167] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(79), 1,
      aux_sym_procedure_definition_token2,
    STATE(13), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym__statement_list,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [209] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(85), 1,
      aux_sym_procedure_definition_token2,
    STATE(9), 1,
      aux_sym__statement_list,
    STATE(14), 1,
      sym_comment,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [251] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(87), 1,
      aux_sym_function_definition_token3,
    STATE(9), 1,
      aux_sym__statement_list,
    STATE(15), 1,
      sym_comment,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [293] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(89), 1,
      aux_sym_function_definition_token3,
    STATE(16), 1,
      sym_comment,
    STATE(17), 1,
      aux_sym__statement_list,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [335] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(91), 1,
      aux_sym_function_definition_token3,
    STATE(9), 1,
      aux_sym__statement_list,
    STATE(17), 1,
      sym_comment,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [377] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(93), 1,
      aux_sym_procedure_definition_token2,
    STATE(18), 1,
      sym_comment,
    STATE(21), 1,
      aux_sym__statement_list,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [419] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(95), 1,
      aux_sym_procedure_definition_token2,
    STATE(19), 1,
      sym_comment,
    STATE(22), 1,
      aux_sym__statement_list,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [461] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(97), 1,
      aux_sym_function_definition_token3,
    STATE(20), 1,
      sym_comment,
    STATE(23), 1,
      aux_sym__statement_list,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [503] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(95), 1,
      aux_sym_procedure_definition_token2,
    STATE(9), 1,
      aux_sym__statement_list,
    STATE(21), 1,
      sym_comment,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [545] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(99), 1,
      aux_sym_procedure_definition_token2,
    STATE(9), 1,
      aux_sym__statement_list,
    STATE(22), 1,
      sym_comment,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [587] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(101), 1,
      aux_sym_function_definition_token3,
    STATE(9), 1,
      aux_sym__statement_list,
    STATE(23), 1,
      sym_comment,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [629] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(103), 1,
      aux_sym_function_definition_token3,
    STATE(24), 1,
      sym_comment,
    STATE(25), 1,
      aux_sym__statement_list,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [671] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(27), 1,
      aux_sym_move_statement_token1,
    ACTIONS(105), 1,
      aux_sym_function_definition_token3,
    STATE(9), 1,
      aux_sym__statement_list,
    STATE(25), 1,
      sym_comment,
    STATE(51), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(60), 1,
      sym__statement,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(19), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(26), 2,
      sym_move_statement,
      sym_unknown_command_statement,
  [713] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(26), 1,
      sym_comment,
    ACTIONS(109), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(107), 9,
      aux_sym_function_definition_token1,
      aux_sym_function_definition_token3,
      aux_sym_procedure_definition_token1,
      aux_sym_procedure_definition_token2,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [738] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(27), 1,
      sym_comment,
    ACTIONS(113), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(111), 9,
      aux_sym_function_definition_token1,
      aux_sym_function_definition_token3,
      aux_sym_procedure_definition_token1,
      aux_sym_procedure_definition_token2,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [763] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(28), 1,
      sym_comment,
    ACTIONS(117), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(115), 9,
      aux_sym_function_definition_token1,
      aux_sym_function_definition_token3,
      aux_sym_procedure_definition_token1,
      aux_sym_procedure_definition_token2,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [788] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(29), 1,
      sym_comment,
    ACTIONS(121), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(119), 9,
      aux_sym_function_definition_token1,
      aux_sym_function_definition_token3,
      aux_sym_procedure_definition_token1,
      aux_sym_procedure_definition_token2,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [813] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(30), 1,
      sym_comment,
    ACTIONS(125), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(123), 7,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [836] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(31), 1,
      sym_comment,
    ACTIONS(129), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(127), 7,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [859] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(32), 1,
      sym_comment,
    ACTIONS(133), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(131), 7,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [882] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(33), 1,
      sym_comment,
    ACTIONS(137), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(135), 7,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [905] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(34), 1,
      sym_comment,
    ACTIONS(141), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(139), 7,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [928] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(35), 1,
      sym_comment,
    ACTIONS(145), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(143), 7,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [951] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(36), 1,
      sym_comment,
    ACTIONS(149), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(147), 7,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [974] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(37), 1,
      sym_comment,
    ACTIONS(153), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(151), 7,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [997] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(38), 1,
      sym_comment,
    ACTIONS(157), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(155), 7,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1020] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(39), 1,
      sym_comment,
    ACTIONS(161), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(159), 7,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1043] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(40), 1,
      sym_comment,
    ACTIONS(165), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(163), 7,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1066] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(41), 1,
      sym_comment,
    ACTIONS(169), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(167), 7,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_definition_token1,
      aux_sym_object_definition_token2,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1089] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(42), 1,
      sym_comment,
    ACTIONS(137), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(135), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1111] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(43), 1,
      sym_comment,
    ACTIONS(149), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(147), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1133] = 10,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(171), 1,
      aux_sym_unknown_command_statement_token1,
    ACTIONS(175), 1,
      sym__eol,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    STATE(44), 1,
      sym_comment,
    STATE(56), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(173), 2,
      sym_number_literal,
      sym_string_literal,
  [1165] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(45), 1,
      sym_comment,
    ACTIONS(125), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(123), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1187] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(46), 1,
      sym_comment,
    ACTIONS(165), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(163), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1209] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(47), 1,
      sym_comment,
    ACTIONS(113), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(111), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1231] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(48), 1,
      sym_comment,
    ACTIONS(133), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(131), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1253] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(49), 1,
      sym_comment,
    ACTIONS(141), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(139), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1275] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(50), 1,
      sym_comment,
    ACTIONS(129), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(127), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1297] = 10,
    ACTIONS(9), 1,
      sym_identifier,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(181), 1,
      aux_sym_unknown_command_statement_token1,
    ACTIONS(183), 1,
      sym__eol,
    STATE(51), 1,
      sym_comment,
    STATE(56), 1,
      aux_sym_unknown_command_statement_repeat1,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(173), 2,
      sym_number_literal,
      sym_string_literal,
  [1329] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(52), 1,
      sym_comment,
    ACTIONS(109), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(107), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1351] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(53), 1,
      sym_comment,
    ACTIONS(121), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(119), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1373] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(54), 1,
      sym_comment,
    ACTIONS(117), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(115), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1395] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(55), 1,
      sym_comment,
    ACTIONS(153), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(151), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1417] = 9,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(185), 1,
      sym_identifier,
    ACTIONS(188), 1,
      aux_sym_unknown_command_statement_token1,
    ACTIONS(193), 1,
      sym__eol,
    STATE(61), 1,
      sym__literal,
    STATE(62), 1,
      sym__expression,
    ACTIONS(190), 2,
      sym_number_literal,
      sym_string_literal,
    STATE(56), 2,
      sym_comment,
      aux_sym_unknown_command_statement_repeat1,
  [1447] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(57), 1,
      sym_comment,
    ACTIONS(145), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(143), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1469] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(58), 1,
      sym_comment,
    ACTIONS(157), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(155), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1491] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(59), 1,
      sym_comment,
    ACTIONS(161), 3,
      ts_builtin_sym_end,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(159), 5,
      aux_sym_function_definition_token1,
      aux_sym_procedure_definition_token1,
      aux_sym_object_declarator_token1,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1513] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(60), 1,
      sym_comment,
    ACTIONS(197), 2,
      sym_number_literal,
      sym_string_literal,
    ACTIONS(195), 4,
      aux_sym_function_definition_token3,
      aux_sym_procedure_definition_token2,
      aux_sym_move_statement_token1,
      sym_identifier,
  [1533] = 5,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(201), 1,
      sym__eol,
    STATE(61), 1,
      sym_comment,
    ACTIONS(199), 4,
      aux_sym_unknown_command_statement_token1,
      sym_identifier,
      sym_number_literal,
      sym_string_literal,
  [1552] = 5,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(205), 1,
      sym__eol,
    STATE(62), 1,
      sym_comment,
    ACTIONS(203), 4,
      aux_sym_unknown_command_statement_token1,
      sym_identifier,
      sym_number_literal,
      sym_string_literal,
  [1571] = 5,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(209), 1,
      sym__eol,
    STATE(63), 1,
      sym_comment,
    ACTIONS(207), 4,
      aux_sym_unknown_command_statement_token1,
      sym_identifier,
      sym_number_literal,
      sym_string_literal,
  [1590] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(211), 1,
      sym_identifier,
    STATE(64), 1,
      sym_comment,
    STATE(83), 1,
      sym__expression,
    STATE(94), 1,
      sym__literal,
    ACTIONS(213), 2,
      sym_number_literal,
      sym_string_literal,
  [1613] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(211), 1,
      sym_identifier,
    STATE(65), 1,
      sym_comment,
    STATE(94), 1,
      sym__literal,
    STATE(104), 1,
      sym__expression,
    ACTIONS(213), 2,
      sym_number_literal,
      sym_string_literal,
  [1636] = 7,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(217), 1,
      sym__eol,
    STATE(66), 1,
      sym_comment,
    STATE(73), 1,
      aux_sym_parameter_list_repeat1,
    STATE(78), 1,
      sym_parameter_list,
  [1658] = 7,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(219), 1,
      sym__eol,
    STATE(67), 1,
      sym_comment,
    STATE(73), 1,
      aux_sym_parameter_list_repeat1,
    STATE(99), 1,
      sym_parameter_list,
  [1680] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(221), 1,
      sym_identifier,
    ACTIONS(223), 1,
      aux_sym_function_definition_token2,
    STATE(68), 1,
      sym_comment,
    STATE(70), 1,
      aux_sym_parameter_list_repeat1,
    STATE(97), 1,
      sym_parameter_list,
  [1702] = 7,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(221), 1,
      sym_identifier,
    ACTIONS(225), 1,
      aux_sym_function_definition_token2,
    STATE(69), 1,
      sym_comment,
    STATE(70), 1,
      aux_sym_parameter_list_repeat1,
    STATE(109), 1,
      sym_parameter_list,
  [1724] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(221), 1,
      sym_identifier,
    ACTIONS(227), 1,
      aux_sym_function_definition_token2,
    STATE(70), 1,
      sym_comment,
    STATE(71), 1,
      aux_sym_parameter_list_repeat1,
  [1743] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(229), 1,
      sym_identifier,
    ACTIONS(232), 1,
      aux_sym_function_definition_token2,
    STATE(71), 2,
      sym_comment,
      aux_sym_parameter_list_repeat1,
  [1760] = 5,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(234), 1,
      sym_identifier,
    ACTIONS(237), 1,
      sym__eol,
    STATE(72), 2,
      sym_comment,
      aux_sym_parameter_list_repeat1,
  [1777] = 6,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(215), 1,
      sym_identifier,
    ACTIONS(239), 1,
      sym__eol,
    STATE(72), 1,
      aux_sym_parameter_list_repeat1,
    STATE(73), 1,
      sym_comment,
  [1796] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    STATE(74), 1,
      sym_comment,
    ACTIONS(241), 2,
      aux_sym_function_definition_token2,
      sym_identifier,
  [1810] = 5,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(241), 1,
      sym_identifier,
    ACTIONS(243), 1,
      sym__eol,
    STATE(75), 1,
      sym_comment,
  [1826] = 4,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(245), 1,
      sym__eol,
    STATE(76), 1,
      sym_comment,
  [1839] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(247), 1,
      anon_sym_SLASH,
    STATE(77), 1,
      sym_comment,
  [1852] = 4,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(249), 1,
      sym__eol,
    STATE(78), 1,
      sym_comment,
  [1865] = 4,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(251), 1,
      sym__eol,
    STATE(79), 1,
      sym_comment,
  [1878] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(253), 1,
      aux_sym_object_declarator_token2,
    STATE(80), 1,
      sym_comment,
  [1891] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(255), 1,
      sym_identifier,
    STATE(81), 1,
      sym_comment,
  [1904] = 4,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(257), 1,
      sym__eol,
    STATE(82), 1,
      sym_comment,
  [1917] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(259), 1,
      aux_sym_move_statement_token2,
    STATE(83), 1,
      sym_comment,
  [1930] = 4,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(261), 1,
      sym__eol,
    STATE(84), 1,
      sym_comment,
  [1943] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(263), 1,
      ts_builtin_sym_end,
    STATE(85), 1,
      sym_comment,
  [1956] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(265), 1,
      sym_identifier,
    STATE(86), 1,
      sym_comment,
  [1969] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(267), 1,
      sym_identifier,
    STATE(87), 1,
      sym_comment,
  [1982] = 4,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(269), 1,
      sym__eol,
    STATE(88), 1,
      sym_comment,
  [1995] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(271), 1,
      sym_identifier,
    STATE(89), 1,
      sym_comment,
  [2008] = 4,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(273), 1,
      sym__eol,
    STATE(90), 1,
      sym_comment,
  [2021] = 4,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(275), 1,
      sym__eol,
    STATE(91), 1,
      sym_comment,
  [2034] = 4,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(277), 1,
      aux_sym_comment_token1,
    STATE(92), 1,
      sym_comment,
  [2047] = 4,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(279), 1,
      sym__eol,
    STATE(93), 1,
      sym_comment,
  [2060] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(201), 1,
      aux_sym_move_statement_token2,
    STATE(94), 1,
      sym_comment,
  [2073] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(281), 1,
      sym_identifier,
    STATE(95), 1,
      sym_comment,
  [2086] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(283), 1,
      sym_identifier,
    STATE(96), 1,
      sym_comment,
  [2099] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(285), 1,
      aux_sym_function_definition_token2,
    STATE(97), 1,
      sym_comment,
  [2112] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(209), 1,
      aux_sym_move_statement_token2,
    STATE(98), 1,
      sym_comment,
  [2125] = 4,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(287), 1,
      sym__eol,
    STATE(99), 1,
      sym_comment,
  [2138] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(289), 1,
      sym_identifier,
    STATE(100), 1,
      sym_comment,
  [2151] = 4,
    ACTIONS(177), 1,
      sym_line_comment,
    ACTIONS(179), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(291), 1,
      sym__eol,
    STATE(101), 1,
      sym_comment,
  [2164] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(293), 1,
      sym_identifier,
    STATE(102), 1,
      sym_comment,
  [2177] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(295), 1,
      sym_identifier,
    STATE(103), 1,
      sym_comment,
  [2190] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(297), 1,
      aux_sym_move_statement_token2,
    STATE(104), 1,
      sym_comment,
  [2203] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(299), 1,
      sym_identifier,
    STATE(105), 1,
      sym_comment,
  [2216] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(301), 1,
      sym_identifier,
    STATE(106), 1,
      sym_comment,
  [2229] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(303), 1,
      aux_sym_object_declarator_token3,
    STATE(107), 1,
      sym_comment,
  [2242] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(305), 1,
      sym_identifier,
    STATE(108), 1,
      sym_comment,
  [2255] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(307), 1,
      aux_sym_function_definition_token2,
    STATE(109), 1,
      sym_comment,
  [2268] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(309), 1,
      sym_identifier,
    STATE(110), 1,
      sym_comment,
  [2281] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      anon_sym_SLASH_STAR,
    ACTIONS(311), 1,
      sym_identifier,
    STATE(111), 1,
      sym_comment,
  [2294] = 1,
    ACTIONS(313), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(9)] = 0,
  [SMALL_STATE(10)] = 41,
  [SMALL_STATE(11)] = 83,
  [SMALL_STATE(12)] = 125,
  [SMALL_STATE(13)] = 167,
  [SMALL_STATE(14)] = 209,
  [SMALL_STATE(15)] = 251,
  [SMALL_STATE(16)] = 293,
  [SMALL_STATE(17)] = 335,
  [SMALL_STATE(18)] = 377,
  [SMALL_STATE(19)] = 419,
  [SMALL_STATE(20)] = 461,
  [SMALL_STATE(21)] = 503,
  [SMALL_STATE(22)] = 545,
  [SMALL_STATE(23)] = 587,
  [SMALL_STATE(24)] = 629,
  [SMALL_STATE(25)] = 671,
  [SMALL_STATE(26)] = 713,
  [SMALL_STATE(27)] = 738,
  [SMALL_STATE(28)] = 763,
  [SMALL_STATE(29)] = 788,
  [SMALL_STATE(30)] = 813,
  [SMALL_STATE(31)] = 836,
  [SMALL_STATE(32)] = 859,
  [SMALL_STATE(33)] = 882,
  [SMALL_STATE(34)] = 905,
  [SMALL_STATE(35)] = 928,
  [SMALL_STATE(36)] = 951,
  [SMALL_STATE(37)] = 974,
  [SMALL_STATE(38)] = 997,
  [SMALL_STATE(39)] = 1020,
  [SMALL_STATE(40)] = 1043,
  [SMALL_STATE(41)] = 1066,
  [SMALL_STATE(42)] = 1089,
  [SMALL_STATE(43)] = 1111,
  [SMALL_STATE(44)] = 1133,
  [SMALL_STATE(45)] = 1165,
  [SMALL_STATE(46)] = 1187,
  [SMALL_STATE(47)] = 1209,
  [SMALL_STATE(48)] = 1231,
  [SMALL_STATE(49)] = 1253,
  [SMALL_STATE(50)] = 1275,
  [SMALL_STATE(51)] = 1297,
  [SMALL_STATE(52)] = 1329,
  [SMALL_STATE(53)] = 1351,
  [SMALL_STATE(54)] = 1373,
  [SMALL_STATE(55)] = 1395,
  [SMALL_STATE(56)] = 1417,
  [SMALL_STATE(57)] = 1447,
  [SMALL_STATE(58)] = 1469,
  [SMALL_STATE(59)] = 1491,
  [SMALL_STATE(60)] = 1513,
  [SMALL_STATE(61)] = 1533,
  [SMALL_STATE(62)] = 1552,
  [SMALL_STATE(63)] = 1571,
  [SMALL_STATE(64)] = 1590,
  [SMALL_STATE(65)] = 1613,
  [SMALL_STATE(66)] = 1636,
  [SMALL_STATE(67)] = 1658,
  [SMALL_STATE(68)] = 1680,
  [SMALL_STATE(69)] = 1702,
  [SMALL_STATE(70)] = 1724,
  [SMALL_STATE(71)] = 1743,
  [SMALL_STATE(72)] = 1760,
  [SMALL_STATE(73)] = 1777,
  [SMALL_STATE(74)] = 1796,
  [SMALL_STATE(75)] = 1810,
  [SMALL_STATE(76)] = 1826,
  [SMALL_STATE(77)] = 1839,
  [SMALL_STATE(78)] = 1852,
  [SMALL_STATE(79)] = 1865,
  [SMALL_STATE(80)] = 1878,
  [SMALL_STATE(81)] = 1891,
  [SMALL_STATE(82)] = 1904,
  [SMALL_STATE(83)] = 1917,
  [SMALL_STATE(84)] = 1930,
  [SMALL_STATE(85)] = 1943,
  [SMALL_STATE(86)] = 1956,
  [SMALL_STATE(87)] = 1969,
  [SMALL_STATE(88)] = 1982,
  [SMALL_STATE(89)] = 1995,
  [SMALL_STATE(90)] = 2008,
  [SMALL_STATE(91)] = 2021,
  [SMALL_STATE(92)] = 2034,
  [SMALL_STATE(93)] = 2047,
  [SMALL_STATE(94)] = 2060,
  [SMALL_STATE(95)] = 2073,
  [SMALL_STATE(96)] = 2086,
  [SMALL_STATE(97)] = 2099,
  [SMALL_STATE(98)] = 2112,
  [SMALL_STATE(99)] = 2125,
  [SMALL_STATE(100)] = 2138,
  [SMALL_STATE(101)] = 2151,
  [SMALL_STATE(102)] = 2164,
  [SMALL_STATE(103)] = 2177,
  [SMALL_STATE(104)] = 2190,
  [SMALL_STATE(105)] = 2203,
  [SMALL_STATE(106)] = 2216,
  [SMALL_STATE(107)] = 2229,
  [SMALL_STATE(108)] = 2242,
  [SMALL_STATE(109)] = 2255,
  [SMALL_STATE(110)] = 2268,
  [SMALL_STATE(111)] = 2281,
  [SMALL_STATE(112)] = 2294,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(86),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(111),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(110),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(103),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(65),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(32),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [38] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(110),
  [41] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(103),
  [44] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(111),
  [49] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(65),
  [52] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(86),
  [62] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(87),
  [65] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(64),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2, 0, 0), SHIFT_REPEAT(61),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__statement_list, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__statement_list, 2, 0, 0), SHIFT_REPEAT(65),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__statement_list, 2, 0, 0), SHIFT_REPEAT(63),
  [79] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [85] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [87] = {.entry = {.count = 1, .reusable = false}}, SHIFT(59),
  [89] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [91] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [95] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [97] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [99] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [101] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [103] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [105] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [107] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__statement, 1, 0, 0),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__statement, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unknown_command_statement, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unknown_command_statement, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_move_statement, 5, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_move_statement, 5, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unknown_command_statement, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unknown_command_statement, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 8, 0, 6),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 8, 0, 6),
  [127] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_procedure_definition, 5, 0, 4),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_definition, 5, 0, 4),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_definition, 2, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_definition, 2, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_definition, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_definition, 3, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__top_level_code, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__top_level_code, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_procedure_definition, 4, 0, 4),
  [149] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_definition, 4, 0, 4),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 6, 0, 5),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 6, 0, 5),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_procedure_definition, 6, 0, 4),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_procedure_definition, 6, 0, 4),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 7, 0, 5),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7, 0, 5),
  [163] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_function_definition, 7, 0, 6),
  [165] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_function_definition, 7, 0, 6),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_object_declarator, 6, 0, 4),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_object_declarator, 6, 0, 4),
  [171] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [173] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [181] = {.entry = {.count = 1, .reusable = false}}, SHIFT(88),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [185] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_unknown_command_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(61),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_unknown_command_statement_repeat1, 2, 0, 0),
  [190] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_unknown_command_statement_repeat1, 2, 0, 0), SHIFT_REPEAT(63),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unknown_command_statement_repeat1, 2, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__statement_list, 1, 0, 0),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__statement_list, 1, 0, 0),
  [199] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__expression, 1, 0, 0),
  [201] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__expression, 1, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_unknown_command_statement_repeat1, 1, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unknown_command_statement_repeat1, 1, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__literal, 1, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__literal, 1, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [213] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [215] = {.entry = {.count = 1, .reusable = false}}, SHIFT(89),
  [217] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(96),
  [223] = {.entry = {.count = 1, .reusable = false}}, SHIFT(95),
  [225] = {.entry = {.count = 1, .reusable = false}}, SHIFT(105),
  [227] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter_list, 1, 0, 1),
  [229] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 3), SHIFT_REPEAT(96),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 3),
  [234] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 3), SHIFT_REPEAT(89),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 3),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter_list, 1, 0, 1),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 2),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_parameter_list_repeat1, 2, 0, 2),
  [245] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [247] = {.entry = {.count = 1, .reusable = false}}, SHIFT(112),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [263] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [277] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [313] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 3, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_dataflex(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
